language: node_js
node_js:
  - "6"
sudo: false
cache:
  directories:
    - node_modules
script: "gulp coverage"
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
